[package]
name = "backup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "6.1.1"
notify-debouncer-full = "0.3.1"
tokio = { version = "1.35.0", features = ["full"] }
